#!/usr/bin/env ruby

platform :ios, '7.0'

xcodeproj 'Staunton'

pod 'KHGravatar'
pod 'KHGravatar/AFNetworking'
pod 'ReactiveCocoa'
pod 'UIView+Helpers', :inhibit_warnings => true
pod 'SocketRocket', :inhibit_warnings => true
